// @ts-nocheck
import { installAdmin } from './admin';
import { installChunkedWorld } from './world';
import { installSky } from './sky';

const stats=document.getElementById('stats') as HTMLElement;
const climateEl=document.getElementById('climate') as HTMLElement;
const msg=document.getElementById('msg') as HTMLElement;
const tools=document.getElementById('tools') as HTMLElement;
const marketRows=document.getElementById('marketRows') as HTMLElement;
const armyInfo=document.getElementById('armyInfo') as HTMLElement;
const techRows=document.getElementById('techRows') as HTMLElement;
const peopleRows=document.getElementById('peopleRows') as HTMLElement;
const weatherInfo=document.getElementById('weatherInfo') as HTMLElement;
const marketBtn=document.getElementById('marketBtn') as HTMLButtonElement;
const armyBtn=document.getElementById('armyBtn') as HTMLButtonElement;
const techBtn=document.getElementById('techBtn') as HTMLButtonElement;
const peopleBtn=document.getElementById('peopleBtn') as HTMLButtonElement;
const weatherBtn=document.getElementById('weatherBtn') as HTMLButtonElement;
const trainBtn=document.getElementById('train') as HTMLButtonElement;
const disband=document.getElementById('disband') as HTMLButtonElement;

import * as THREE from 'three';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc4cc);scene.fog=new THREE.Fog(0x9fc4cc,55,125);const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,200);camera.position.set(10,9,14);const renderer=new THREE.WebGLRenderer({antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xd9efff,0x20351f,2.2));const sun=new THREE.DirectionalLight(0xfff4d6,2.8);sun.position.set(18,30,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-60;sun.shadow.camera.right=60;sun.shadow.camera.top=60;sun.shadow.camera.bottom=-60;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.MeshStandardMaterial({color:0x174d2a,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);scene.add(new THREE.GridHelper(120,120,0x6a9675,0x315f3c));
const updateWorldChunks=installChunkedWorld(scene,camera);installSky(scene,camera);
const buildings:any[]=[],occupied=new Map(),villagers:any[]=[],ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),keys=new Set();const resources:any={wood:120,food:100,stone:80,metal:40,gold:250},capacity={wood:200,food:200,stone:200,metal:150,gold:1000},prices={wood:4,food:3,stone:5,metal:10};let yaw=.62,pitch=-.38,locked=false,rotation=0,selected='house',soldiers=0,research=0,morale=100,buildId=0,freeBuild=false;
const techs:any={masonry:{name:'Maçonnerie',cost:25,req:[],desc:'+20% vitesse de construction'},agriculture:{name:'Agriculture avancée',cost:35,req:[],desc:'Débloque moulin et boulangerie'},metallurgy:{name:'Métallurgie',cost:45,req:['masonry'],desc:'Débloque caserne et tour'},commerce:{name:'Commerce organisé',cost:55,req:['masonry'],desc:'Prix commerciaux -10%'},engineering:{name:'Ingénierie',cost:75,req:['metallurgy'],desc:'Débloque remparts et scierie améliorée'},scholarship:{name:'Érudition',cost:90,req:['agriculture','commerce'],desc:'Recherche x2'}};
const types:any={house:{name:'Maison',icon:'🏠',size:3,cost:{wood:20,stone:5},pop:4,work:5},farm:{name:'Ferme',icon:'🌾',size:4,cost:{wood:15,gold:5},prod:{food:5},work:5},lumber:{name:'Scierie',icon:'🪵',size:3,cost:{wood:25,stone:10},prod:{wood:5},work:6},quarry:{name:'Carrière',icon:'🪨',size:3,cost:{wood:20,stone:10},prod:{stone:4},work:6},mine:{name:'Mine',icon:'⛏️',size:3,cost:{wood:30,stone:15},prod:{metal:3},work:8},market:{name:'Marché',icon:'🪙',size:3,cost:{wood:30,stone:15},work:6},granary:{name:'Grenier',icon:'🌾',size:3,cost:{wood:25,stone:10},storage:{food:150},work:4},warehouse:{name:'Entrepôt',icon:'📦',size:4,cost:{wood:35,stone:20},storage:{wood:150,stone:100,metal:80},work:5},vault:{name:'Trésor',icon:'🏦',size:3,cost:{stone:40,metal:10},storage:{gold:500},work:4},blacksmith:{name:'Forge',icon:'⚒️',size:3,cost:{wood:25,stone:25,metal:5},prod:{metal:2},work:8},tavern:{name:'Taverne',icon:'🍺',size:3,cost:{wood:35,stone:10},pop:2,work:5},mill:{name:'Moulin',icon:'🌬️',size:3,cost:{wood:35,stone:15},prod:{food:9},work:6,tech:'agriculture'},bakery:{name:'Boulangerie',icon:'🥖',size:3,cost:{wood:30,stone:20,food:20},prod:{food:12},work:7,tech:'agriculture'},barracks:{name:'Caserne',icon:'⚔️',size:4,cost:{wood:50,stone:40,metal:20},work:10,tech:'metallurgy'},tower:{name:'Tour de garde',icon:'🗼',size:3,cost:{stone:60,wood:20,metal:10},work:8,tech:'metallurgy'},wall:{name:'Remparts',icon:'🧱',size:3,cost:{stone:70,wood:15},work:10,tech:'engineering'},school:{name:'École',icon:'🏫',size:3,cost:{wood:30,stone:15,gold:10},research:0.5,work:6},university:{name:'Université',icon:'📚',size:4,cost:{wood:60,stone:50,gold:80},research:3,work:12,tech:'school'},windmill:{name:'Scierie améliorée',icon:'🏭',size:4,cost:{wood:70,stone:35,metal:15},prod:{wood:12},work:10,tech:'engineering'}};
const material=c=>new THREE.MeshStandardMaterial({color:c,roughness:.78,metalness:0});function box(w,h,d,c,x=0,y=0,z=0){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(c));m.position.set(x,y+h/2,z);m.castShadow=true;m.receiveShadow=true;return m}function visual(type,x,z){const g=new THREE.Group();const addBox=(w,h,d,c)=>g.add(box(w,h,d,c));const cyl=(r,h,c,x=0,y=0,z=0,s=10)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,s),material(c));m.position.set(x,y+h/2,z);m.castShadow=true;g.add(m);return m};if(type==='house'){addBox(2.8,2.2,2.8,0x8b5a3c);const q=new THREE.Mesh(new THREE.ConeGeometry(2.2,1.5,4),material(0x59332a));q.rotation.y=Math.PI/4;q.position.y=2.95;g.add(q)}else if(type==='farm')addBox(3.7,.18,3.7,0x47743b);else if(type==='school'){addBox(2.8,2.4,2.7,0x806044);const q=new THREE.Mesh(new THREE.ConeGeometry(2.0,1.2,4),material(0x4f3027));q.rotation.y=Math.PI/4;q.position.y=3;g.add(q);addBox(.7,1.2,.1,0x3d3029,0,.25,1.36);cyl(.12,.9,0xd1aa54,0,2.5,0,8)}else if(type==='university'){addBox(3.6,2.6,3.6,0x777);const q=new THREE.Mesh(new THREE.ConeGeometry(2.5,1.6,4),material(0x59332a));q.rotation.y=Math.PI/4;q.position.y=3.4;g.add(q);cyl(.18,.9,0x5a3928,0,3.15,0,8);addBox(.1,1.45,.1,0xc59a52,0,4,0)}else{addBox(2.8,1.8,2.7,type==='quarry'?0x77716a:0x7a4d2d)}g.position.set(x,0,z);g.rotation.y=rotation;scene.add(g);return g}
function storage(){const c:any={...capacity};buildings.forEach(b=>{if(b.storage)Object.entries(b.storage).forEach(([r,v])=>c[r]+=v)});return c}function population(){return 5+buildings.reduce((n,b)=>n+(b.pop||0),0)}function usedWorkers(){return buildings.reduce((n,b)=>n+(b.progress<1?(b.workers||0):0),0)}function freeWorkers(){return freeBuild?9999:Math.max(0,population()-soldiers-usedWorkers())}function canPay(c){return freeBuild||Object.entries(c).every(([r,v])=>resources[r]>=v)}function pay(c){if(freeBuild)return;Object.entries(c).forEach(([r,v])=>resources[r]-=v)}function cells(type,gx,gz){const n=types[type].size,h=Math.floor(n/2),out=[];for(let x=gx-h;x<gx-h+n;x++)for(let z=gz-h;z<gz-h+n;z++)out.push([x,z]);return out}function add(type,x,z){const t=types[type],gx=Math.floor(x+.5),gz=Math.floor(z+.5),cs=cells(type,gx,gz);if(t.tech&&!techs[t.tech]?.done)return toast('🔒 Technologie requise');if(cs.some(c=>occupied.has(c.join(','))))return toast('❌ Emplacement occupé');if(!canPay(t.cost))return toast('❌ Ressources insuffisantes');if(freeWorkers()<(t.work||5))return toast('👷 Travailleurs libres insuffisants');pay(t.cost);const v=visual(type,gx,gz);const b={id:++buildId,type,x:gx,z:gz,cells:cs,visual:v,storage:t.storage,prod:t.prod,pop:t.pop||0,workers:t.work||5,progress:0,buildTime:Math.max(5,(t.work||5)*1.5),hp:100,maxHp:100};v.userData.building=b;buildings.push(b);cs.forEach(c=>occupied.set(c.join(','),b));updateUI();return true}
function renderTech(){techRows.innerHTML='<div>Recherche : <b>'+research.toFixed(1)+'</b> 🔬</div>';Object.entries(techs as any).forEach(([id,t]:any)=>{const row=document.createElement('section');const req=t.req.every(x=>techs[x].done);row.innerHTML='<b>'+(t.done?'✅':'💠')+' '+t.name+'</b> — '+t.cost+'<br><span class="small">'+t.desc+'</span>';if(!t.done){const btn=document.createElement('button');btn.textContent=req?'Développer':'Prérequis manquants';btn.disabled=!req;btn.onclick=()=>{if(research<t.cost)return toast('Recherche insuffisante');research-=t.cost;t.done=true;renderTech();refreshTools()};row.appendChild(btn)}techRows.appendChild(row)})}function refreshTools(){tools.innerHTML='';Object.entries(types as any).forEach(([id,t]:any)=>{if(t.tech&&!techs[t.tech]?.done)return;const b=document.createElement('button');b.textContent=t.icon+' '+t.name;b.onclick=()=>selected=id;tools.appendChild(b)})}
function updateUI(){Object.keys(resources).forEach(r=>document.getElementById(r).textContent=String(Math.floor(resources[r])));stats.textContent='Population : '+population()+' · Travailleurs libres : '+freeWorkers()+' · Soldats : '+soldiers+' · Bâtiments : '+buildings.length+' · Recherche : '+research.toFixed(1);weatherEl.textContent=weatherDefs[currentWeather].i+' '+weatherDefs[currentWeather].n;climateEl.textContent='🌡️ '+Math.round(climate.t*100)+'% · 💧 '+Math.round(climate.h*100)+'% · 💨 '+Math.round(climate.w*100)+'%';renderTech()}function toast(t){msg.textContent=t;msg.style.opacity='1';clearTimeout((window as any).toastTimer);(window as any).toastTimer=setTimeout(()=>msg.style.opacity='0',1800)}
const seasons:any={printemps:{t:.55,h:.62,w:.35},ete:{t:.82,h:.48,w:.28},automne:{t:.48,h:.72,w:.48},hiver:{t:.22,h:.68,w:.42}};const weatherDefs:any={beau:{n:'Beau temps',i:'☀️',t:[.6,.95],h:[.25,.7],w:[.05,.35],p:1},eclaircies:{n:'Éclaircies',i:'🌤️',t:[.45,.85],h:[.4,.8],w:[.1,.45],p:.95},nuageux:{n:'Nuageux',i:'☁️',t:[.35,.75],h:[.5,.9],w:[.1,.5],p:.9},pluie:{n:'Pluie',i:'🌧️',t:[.35,.7],h:[.72,1],w:[.15,.55],p:.8},torrentielle:{n:'Pluie torrentielle',i:'🌧️',t:[.35,.75],h:[.88,1],w:[.25,.7],p:.55,d:1,f:1},neige:{n:'Neige',i:'🌨️',t:[0,.35],h:[.55,.95],w:[.15,.55],p:.55,d:.25},blizzard:{n:'Tempête de neige',i:'❄️',t:[0,.28],h:[.65,1],w:[.65,1],p:.35,d:1},orage:{n:'Orage',i:'⛈️',t:[.3,.75],h:[.75,1],w:[.35,.85],p:.7,d:1.5,l:1},ouragan:{n:'Ouragan',i:'🌀',t:[.55,.95],h:[.65,1],w:[.9,1],p:.25,d:4},canicule:{n:'Canicule',i:'🔥',t:[.9,1],h:[.15,.55],w:[.05,.35],p:.65,d:.7}};let climate={t:.55,h:.62,w:.35},season='printemps',currentWeather='beau';const weatherEl=document.getElementById('weather') as HTMLElement;let weatherClock=0,nextWeather=300,seasonClock=0;function chooseWeather(){const names=Object.keys(weatherDefs);const weights=names.map(k=>{const d=weatherDefs[k],a=(climate.t>=d.t[0]&&climate.t<=d.t[1])?2:.35,b=(climate.h>=d.h[0]&&climate.h<=d.h[1])?2:.35,c=(climate.w>=d.w[0]&&climate.w<=d.w[1])?2:.35;return a*b*c});let r=Math.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<names.length;i++){r-=weights[i];if(r<=0){currentWeather=names[i];break}}weatherClock=0;nextWeather=240+Math.random()*360}function climateTick(dt){weatherClock+=dt;seasonClock+=dt;if(seasonClock>=180)seasonClock=0;if(weatherClock>=nextWeather)chooseWeather();const s=seasons[season];const k=Math.max(240,nextWeather);climate.t=Math.max(0,Math.min(1,climate.t+((s.t+(Math.random()-.5)*.18)-climate.t)*dt/k));climate.h=Math.max(0,Math.min(1,climate.h+((s.h+(Math.random()-.5)*.2)-climate.h)*dt/k));climate.w=Math.max(0,Math.min(1,climate.w+((s.w+(Math.random()-.5)*.2)-climate.w)*dt/k))}function weatherTick(){const d=weatherDefs[currentWeather],cap=storage();buildings.slice().forEach(b=>{if(b.progress<1)return;if(b.prod)Object.entries(b.prod).forEach(([r,v])=>{resources[r]=Math.min(cap[r],resources[r]+v*d.p/2)});if(d.d&&Math.random()<Math.min(.9,.12*d.d)){b.hp=Math.max(0,b.hp-(2+Math.random()*5)*d.d);if(b.hp===0){scene.remove(b.visual);b.cells.forEach(c=>occupied.delete(c.join(',')));const i=buildings.indexOf(b);if(i>=0)buildings.splice(i,1)}}});if(d.f&&Math.random()<.12)toast('🌊 Risque d’inondation !')}function renderWeather(){const d=weatherDefs[currentWeather];weatherInfo.innerHTML='<h3>'+d.i+' '+d.n+'</h3>🌡️ Température<div class="bar"><i style="width:'+(climate.t*100)+'%"></i></div>💧 Humidité<div class="bar"><i style="width:'+(climate.h*100)+'%"></i></div>💨 Vent<div class="bar"><i style="width:'+(climate.w*100)+'%"></i></div>'}
const villagerBodyGeo=new THREE.BoxGeometry(.38,.7,.3),villagerHeadGeo=new THREE.SphereGeometry(.2,6,6),villagerBodyMat=material(0xc89d72),villagerHeadMat=material(0xd8b18a);function createVillager(id){const g=new THREE.Group(),body=new THREE.Mesh(villagerBodyGeo,villagerBodyMat),head=new THREE.Mesh(villagerHeadGeo,villagerHeadMat);body.position.y=.35;head.position.y=.85;g.add(body,head);g.position.set((Math.random()-.5)*12,0,(Math.random()-.5)*12);scene.add(g);return{id,mesh:g,target:new THREE.Vector3((Math.random()-.5)*18,0,(Math.random()-.5)*18),speed:1+Math.random(),hunger:100,energy:100,state:'Se promène',job:'Libre'}}function syncVillagers(){const count=Math.max(0,population()-soldiers);while(villagers.length<count)villagers.push(createVillager(villagers.length+1));while(villagers.length>count)scene.remove(villagers.pop().mesh)}function moveVillagers(dt){villagers.forEach(v=>{const d=v.target.clone().sub(v.mesh.position);d.y=0;if(d.lengthSq()>.0625)v.mesh.position.addScaledVector(d.normalize(),.035*v.speed*Math.min(dt*60,2))})}
setInterval(()=>{buildings.forEach(b=>{if(b.progress<1){b.progress=Math.min(1,b.progress+1/b.buildTime);b.visual.scale.setScalar(.72+.28*b.progress)}});weatherTick();if(soldiers){if(resources.food>=soldiers)resources.food-=soldiers;else{morale=Math.max(0,morale-5);soldiers=Math.max(0,soldiers-1)}}if(buildings.some(b=>b.type==='school'))research+=.5;if(buildings.some(b=>b.type==='university'))research+=3;syncVillagers();updateUI();renderWeather()},1000);
refreshTools();syncVillagers();updateUI();renderWeather();marketBtn.onclick=()=>{};armyBtn.onclick=()=>{};techBtn.onclick=()=>{document.getElementById('tech').classList.toggle('open');renderTech()};peopleBtn.onclick=()=>{};weatherBtn.onclick=()=>{};trainBtn.onclick=()=>{};disband.onclick=()=>{if(soldiers){soldiers--;updateUI()}};renderer.domElement.onclick=()=>renderer.domElement.requestPointerLock?.();document.onpointerlockchange=()=>locked=document.pointerLockElement===renderer.domElement;document.onmousemove=e=>{if(locked){yaw-=e.movementX*.0025;pitch=Math.max(-1.45,Math.min(1.45,pitch-e.movementY*.0025))}};onkeydown=e=>{keys.add(e.code);if(e.code==='KeyR')rotation+=Math.PI/2};onkeyup=e=>keys.delete(e.code);renderer.domElement.onwheel=e=>{e.preventDefault();camera.position.y=Math.max(1.2,camera.position.y+e.deltaY*.01)};let fps=60,last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;fps=dt>0?1/dt:60;climateTick(dt);updateWorldChunks();const speed=keys.has('ShiftLeft')||keys.has('ShiftRight')?12:6,move=new THREE.Vector3();if(keys.has('KeyW'))move.z-=1;if(keys.has('KeyS'))move.z+=1;if(keys.has('KeyD'))move.x+=1;if(keys.has('KeyA'))move.x-=1;if(move.lengthSq())camera.position.addScaledVector(move.normalize(),speed*dt);camera.position.y=Math.max(1.2,camera.position.y);camera.lookAt(camera.position.x,0,camera.position.z);moveVillagers(dt);renderer.render(scene,camera)}requestAnimationFrame(animate);
installAdmin({resources,capacity,buildings,villagers,occupied,techs,scene,storage,population,updateUI,refreshTools,renderTech,chooseWeather,get soldiers(){return soldiers},set soldiers(v){soldiers=v},get research(){return research},set research(v){research=v},get currentWeather(){return currentWeather},set currentWeather(v){if(weatherDefs[v])currentWeather=v},get freeBuild(){return freeBuild},set freeBuild(v){freeBuild=v},fps:()=>fps});
onresize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)};
